version: '3'

services:
  db:
    container_name: cow_db
    image: mariadb:jammy
    # volumes:
    #   - ./db:/var/lib/mysql
    environment:
      - MARIADB_USER=andre
      - MARIADB_PASSWORD=Admin123
      - MARIADB_ROOT_PASSWORD=Admin123
      - MARIADB_DATABASE=cow_db
    ports:
      - "3306:3306"
