# version: '3.4'

services:
  db:
    container_name: cow_db
    image: mariadb:jammy
    volumes:
      - cow_vol:/var/lib/mysql
    environment:
      - MARIADB_USER=andre
      - MARIADB_PASSWORD=Admin123
      - MARIADB_ROOT_PASSWORD=Admin123
      - MARIADB_DATABASE=cow_db
    ports:
      - "3306:3306"

volumes:
  cow_vol:
    external: true
    
#   dockergoproject:
#     image: dockergoproject
#     build:
#       context: .
#       dockerfile: ./Dockerfile
#     ports:
#       - 8080:8080
