name: LOCAL
mysql:
  user: cow
  password: Admin123
  port: 3306
  host: localhost
  schema: cow_test_db
users-api:
  url: http://localhost:9002
  timeout: 5s
job:
  users:
    active: true
    expression: 0/1 * * * *