name: PRODUCTION
mysql:
  user: cow
  password: Admin123
  port: 3306
  host: cow_prod_db
  schema: cow_prod_db
users-api:
  url: http://users_prod_api:8080
  timeout: 5s
job:
  users:
    active: true
    expression: 0/1 * * * *