name: TEST
mysql:
  user: cow
  password: Admin123
  port: 3306
  host: cow_test_db
  schema: cow_test_db
users-api:
  url: http://cow_sso_api_test:8080
  timeout: 5s
job:
  users:
    active: true
    expression: 0/1 * * * *